import { Concert } from '@/types';

export const CAMBODIAN_CONCERTS: Concert[] = [
  {
    id: 'kh-concert-001',
    title: 'Skull Tour: Born in Battambang Live',
    artist: 'VannDa (វណ្ណដា)',
    description:
      'A historic, high-energy headline show by Cambodia’s global hip-hop pioneer featuring live traditional pinpeat drums, surprise guest MCs, and thunderous sound production.',
    venue: 'CT Live Main Hall (Diamond Island / Koh Pich)',
    city: 'Phnom Penh',
    date: '2026-11-14T19:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1000&q=80',
    featured: true,
    status: 'SCHEDULED',
    startingPrice: 15,
    totalAvailable: 730,
    categories: [
      {
        id: 'cat-vd-01',
        name: 'Fanpit',
        price: 45,
        color: '#ec4899',
        description: 'Front stage mosh pit. Direct proximity to VannDa with exclusive Tour Lanyard.',
        perks: ['Front Row Catwalk Access', 'VIP Tour Lanyard', 'Priority Early Entry (5:00 PM)'],
        totalCapacity: 60,
        soldCount: 8,
        activeReserved: 0,
        available: 52,
      },
      {
        id: 'cat-vd-02',
        name: 'Platinum',
        price: 35,
        color: '#8b5cf6',
        description: 'Lower tier center seating with direct stage line-of-sight and air-conditioned lounge access.',
        perks: ['Lower Tier Center Rows 1-10', 'Private VIP Lounge', 'Padded Club Seats'],
        totalCapacity: 120,
        soldCount: 24,
        activeReserved: 0,
        available: 96,
      },
      {
        id: 'cat-vd-03',
        name: 'Gold',
        price: 25,
        color: '#eab308',
        description: 'Mid Tier elevated elevation with clear acoustic projection.',
        perks: ['Elevated Mid-Tier Seating', 'Direct Line-of-Sight to Stage'],
        totalCapacity: 200,
        soldCount: 45,
        activeReserved: 0,
        available: 155,
      },
      {
        id: 'cat-vd-04',
        name: 'Silver',
        price: 15,
        color: '#94a3b8',
        description: 'General admission hall view with full acoustic delay towers.',
        perks: ['General Admission Seating', 'Panoramic Lightshow View'],
        totalCapacity: 350,
        soldCount: 60,
        activeReserved: 0,
        available: 290,
      },
    ],
  },
  {
    id: 'kh-concert-002',
    title: 'Kings of Khmer Pop & Hip-Hop Mega Live',
    artist: 'Preap Sovath & G-Devith',
    description:
      'A groundbreaking crossover concert bridging three decades of legendary Khmer pop with modern trap beats and high-octane choreography.',
    venue: 'Morodok Techo National Stadium Live Arena',
    city: 'Phnom Penh',
    date: '2026-12-05T19:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&q=80',
    featured: true,
    status: 'SCHEDULED',
    startingPrice: 10,
    totalAvailable: 530,
    categories: [
      {
        id: 'cat-ps-01',
        name: 'Fanpit',
        price: 50,
        color: '#ec4899',
        perks: ['Direct Pit Access', 'Synchronized LED Wristband'],
        totalCapacity: 50,
        soldCount: 12,
        activeReserved: 0,
        available: 38,
      },
      {
        id: 'cat-ps-02',
        name: 'Platinum',
        price: 35,
        color: '#8b5cf6',
        perks: ['Level 2 Premium Concourse', 'Padded Stadium Seats'],
        totalCapacity: 100,
        soldCount: 18,
        activeReserved: 0,
        available: 82,
      },
      {
        id: 'cat-ps-03',
        name: 'Gold',
        price: 20,
        color: '#eab308',
        perks: ['Central Sideline View'],
        totalCapacity: 180,
        soldCount: 30,
        activeReserved: 0,
        available: 150,
      },
      {
        id: 'cat-ps-04',
        name: 'Silver',
        price: 10,
        color: '#94a3b8',
        perks: ['Upper Concourse Seating'],
        totalCapacity: 300,
        soldCount: 50,
        activeReserved: 0,
        available: 250,
      },
    ],
  },
  {
    id: 'kh-concert-003',
    title: 'Golden Era Angkor Symphony & Acoustic Night',
    artist: 'Sinn Sisamouth Legacy Orchestra ft. Meng Keo Pichenda',
    description:
      'A magical evening under the stars near the ancient temples honoring the Golden Age of 1960s Cambodian rock and classical orchestral melodies.',
    venue: 'Angkor Heritage Cultural Amphitheatre',
    city: 'Siem Reap',
    date: '2026-10-25T18:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
    featured: true,
    status: 'SCHEDULED',
    startingPrice: 15,
    totalAvailable: 420,
    categories: [
      {
        id: 'cat-ss-01',
        name: 'Fanpit',
        price: 60,
        color: '#ec4899',
        perks: ['Royal Circle Front Row', 'Traditional Khmer Welcome Ceremony'],
        totalCapacity: 40,
        soldCount: 5,
        activeReserved: 0,
        available: 35,
      },
      {
        id: 'cat-ss-02',
        name: 'Platinum',
        price: 40,
        color: '#8b5cf6',
        perks: ['Center Tiered Seating', 'Lotus Tea Service'],
        totalCapacity: 80,
        soldCount: 15,
        activeReserved: 0,
        available: 65,
      },
      {
        id: 'cat-ss-03',
        name: 'Gold',
        price: 25,
        color: '#eab308',
        perks: ['Garden Terrace View'],
        totalCapacity: 150,
        soldCount: 22,
        activeReserved: 0,
        available: 128,
      },
      {
        id: 'cat-ss-04',
        name: 'Silver',
        price: 15,
        color: '#94a3b8',
        perks: ['Open Lawn Seating'],
        totalCapacity: 250,
        soldCount: 40,
        activeReserved: 0,
        available: 210,
      },
    ],
  },
  {
    id: 'kh-concert-004',
    title: 'Sunset Acoustic & R&B Riverfront Live',
    artist: 'Tena x Sophia Kao x Suly Pheng',
    description:
      'An intimate sunset concert along the Sangke river featuring soulful vocals, acoustic guitars, and modern Cambodian neo-soul favorites.',
    venue: 'Sangke Riverfront Amphitheatre',
    city: 'Battambang',
    date: '2026-11-28T18:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1000&q=80',
    featured: false,
    status: 'SCHEDULED',
    startingPrice: 8,
    totalAvailable: 475,
    categories: [
      {
        id: 'cat-tn-01',
        name: 'Fanpit',
        price: 30,
        color: '#ec4899',
        perks: ['Riverside Front Row', 'Backstage Meet & Greet Pass'],
        totalCapacity: 45,
        soldCount: 10,
        activeReserved: 0,
        available: 35,
      },
      {
        id: 'cat-tn-02',
        name: 'Platinum',
        price: 20,
        color: '#8b5cf6',
        perks: ['Reserved Covered Seating'],
        totalCapacity: 90,
        soldCount: 20,
        activeReserved: 0,
        available: 70,
      },
      {
        id: 'cat-tn-03',
        name: 'Gold',
        price: 15,
        color: '#eab308',
        perks: ['Mid Tier Clear Sightlines'],
        totalCapacity: 160,
        soldCount: 30,
        activeReserved: 0,
        available: 130,
      },
      {
        id: 'cat-tn-04',
        name: 'Silver',
        price: 8,
        color: '#94a3b8',
        perks: ['Riverside Lawn Admission'],
        totalCapacity: 280,
        soldCount: 45,
        activeReserved: 0,
        available: 235,
      },
    ],
  },
  {
    id: 'kh-concert-005',
    title: 'Coastal Beats & Indie Rock Festival',
    artist: 'Sai & SmallWorld SmallBand (SWSB)',
    description:
      'A vibrant open-air beachside concert bringing uplifting original Khmer indie rock, ocean breeze, and charity fundraising for pediatric healthcare.',
    venue: 'Bay of Lights Ocean Arena',
    city: 'Preah Sihanouk',
    date: '2026-12-20T17:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&q=80',
    featured: false,
    status: 'SCHEDULED',
    startingPrice: 10,
    totalAvailable: 535,
    categories: [
      {
        id: 'cat-sw-01',
        name: 'Fanpit',
        price: 35,
        color: '#ec4899',
        perks: ['Beach Stage Front Row', 'Charity T-Shirt Included'],
        totalCapacity: 50,
        soldCount: 5,
        activeReserved: 0,
        available: 45,
      },
      {
        id: 'cat-sw-02',
        name: 'Platinum',
        price: 25,
        color: '#8b5cf6',
        perks: ['VIP Deck Access', 'Complimentary Coconut Drink'],
        totalCapacity: 100,
        soldCount: 15,
        activeReserved: 0,
        available: 85,
      },
      {
        id: 'cat-sw-03',
        name: 'Gold',
        price: 15,
        color: '#eab308',
        perks: ['Festival Lawn Access'],
        totalCapacity: 150,
        soldCount: 20,
        activeReserved: 0,
        available: 130,
      },
      {
        id: 'cat-sw-04',
        name: 'Silver',
        price: 10,
        color: '#94a3b8',
        perks: ['General Beach Admission'],
        totalCapacity: 300,
        soldCount: 40,
        activeReserved: 0,
        available: 260,
      },
    ],
  },
  {
    id: 'kh-concert-006',
    title: 'Bokor Mountain Mist Jam & Hip-Hop Summit',
    artist: 'RuthKo & KlapYaHandz All-Stars',
    description:
      'A cool mountain breeze festival perched 1,000 meters above sea level on Bokor Plateau, featuring underground hip-hop, turntablism, and live beats.',
    venue: 'Bokor Plateau Mountain Amphitheatre',
    city: 'Kampot',
    date: '2027-01-10T17:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
    featured: false,
    status: 'SCHEDULED',
    startingPrice: 8,
    totalAvailable: 410,
    categories: [
      {
        id: 'cat-rk-01',
        name: 'Fanpit',
        price: 28,
        color: '#ec4899',
        perks: ['Stage Pit Standing', 'KlapYaHandz Merch Pack'],
        totalCapacity: 40,
        soldCount: 8,
        activeReserved: 0,
        available: 32,
      },
      {
        id: 'cat-rk-02',
        name: 'Platinum',
        price: 20,
        color: '#8b5cf6',
        perks: ['Scenic Veranda Seating'],
        totalCapacity: 80,
        soldCount: 12,
        activeReserved: 0,
        available: 68,
      },
      {
        id: 'cat-rk-03',
        name: 'Gold',
        price: 14,
        color: '#eab308',
        perks: ['Stone Amphitheatre Seating'],
        totalCapacity: 120,
        soldCount: 25,
        activeReserved: 0,
        available: 95,
      },
      {
        id: 'cat-rk-04',
        name: 'Silver',
        price: 8,
        color: '#94a3b8',
        perks: ['General Ridge Admission'],
        totalCapacity: 250,
        soldCount: 30,
        activeReserved: 0,
        available: 220,
      },
    ],
  },
];
