FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY .npmrc* ./
RUN npm install --legacy-peer-deps
COPY . .
ENV DATABASE_URL="postgresql://postgres:postgres@localhost:5432/test?schema=public"
RUN npx prisma generate
EXPOSE 5000
CMD ["npx", "tsx", "server/index.ts"]
