FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY .npmrc* ./
RUN npm install --legacy-peer-deps
COPY prisma ./prisma
ENV DATABASE_URL="postgresql://postgres:postgres@localhost:5432/test?schema=public"
RUN npx prisma generate
CMD ["npx", "prisma", "db", "push"]
